name: CI Test Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: findus
          POSTGRES_PASSWORD: findus123
          POSTGRES_DB: findus_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        env:
          DB_HOST: ${{ secrets.TEST_DB_HOST }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_PORT: ${{ secrets.TEST_DB_PORT }}
          DB_USER: ${{ secrets.TEST_DB_USER }}
          DJANGO_ENV: ${{ secrets.TEST_DJANGO_ENV }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.TEST_DJANGO_SETTINGS_MODULE }}
          SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
        run: |
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENVs
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "DJANGO_ENV=$DJANGO_ENV" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE" >> $GITHUB_ENV
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV

      - name: Run tests
        run: |
          export DJANGO_SETTINGS_MODULE=config.settings.local
          pytest --cov=apps --cov-report=xml

      - name: Check coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          coverage_command: pytest --cov=apps
          coverage_variable: COVERAGE
          coverage_target: 60%